### ISSUE TITLE
Website Redesign Tasklist

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#558]
# Website Redesign

Fontsource has grown a lot and so have our needs. We're moving to a new website that aims to improve user experience and introduce new functionality that clears a lot of issues in the repository. 

We've got a bunch of new design mockups sponsored by the awesome folks at @jsdelivr which can be viewed at each issue below for their respective pages.

## Tech Stack

Since this is a significant change, we're moving away from our current Next.js setup and starting from scratch. We'll be relying on [Remix](https://remix.run/) + [Fly.io](https://fly.io/) for it's optimal SSR flexibility. Likewise, we'll be moving over to [Mantine](https://mantine.dev/) for its easy to use and accessible components.

## Task List

- [x] https://github.com/fontsource/fontsource/issues/551
- [x] https://github.com/fontsource/fontsource/issues/552
- [x] https://github.com/fontsource/fontsource/issues/553
- [x] https://github.com/fontsource/fontsource/issues/554
- [ ] https://github.com/fontsource/fontsource/issues/555
- [x] https://github.com/fontsource/fontsource/issues/556
- [ ] https://github.com/fontsource/fontsource/issues/557

The full project board can be found here: [Fontsource Project Board](https://github.com/orgs/fontsource/projects/1)
You can follow the progress in our [Discord](https://discord.gg/pJgkn7xjAj) or website branch at [beta.fontsource.org](https://beta.fontsource.org/).
